build:
  main: cmd/armor/main.go
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
  
archives:
  - id: armor
    format: tgz
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: 64-bit
      darwin: macos
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}_checksum.txt"
    
release:
  draft: true
