address: :7000
plugins:
  - name: logger
  - name: redirect
    from: /docs
    to: /docs/api/currency/convert
    code: 302
  - name: static
    root: /Users/vr/Projects/labstack/web/build
    html5: true